name: Minikube E2E

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup dotnet SDK 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Setup dotnet SDK 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'          
      - name: Minikube
        run: minikube start
      - name: Test
        run: |
          #env K8S_E2E_MINIKUBE=1 dotnet test tests/E2E.Tests
          dotnet test tests/E2E.Tests > log
          cat log
          grep '\[SKIP\]$' log > skip
          if [ -s skip ];
            echo "CASES MUST NOT BE SKIPPED"
            exit 1
          fi

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
